/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "idl.h"

bool_t
xdr_operands (XDR *xdrs, operands *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->op1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->op2))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->operator))
		 return FALSE;
	return TRUE;
}
